### ISSUE TITLE
Possible fix for not need click in CLOSE

### ISSUE THREAD

**Issue by nathanparra** [popeen/Classic-Volume-Mixer#16]
Here is the problem, to make it easier to understand I reproduced it on video
https://www.youtube.com/watch?v=ewusb7sKQ1w

**Comment by graefjk** [comment]
This problem occurs because when closing the volume mixer by clicking away, the volume mixer is not actually closed but is just turned invisible.
This is done because in some cases when opening sndvol you can see it opening in the upper left corner before jumping to the lower right. Just turning the mixer invisible circumvents this issue.
However it seems that Windows 10 and presumable 8 use sndvol for there volume mixer in some capacity. 
Because sndvol is invisible, the native volume mixer also seems to be invisible.
